# Generated by Django 3.1.7 on 2021-03-22 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20210321_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_post',
            field=models.ManyToManyField(blank=True, related_name='read_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
